---
title: "Tutoriales"
knitr:
  opts_chunk:
    echo: false
    message: false
    warning: false
---

## Introducción a Github para Investigador(a|e)s

#### Aprende cómo usar GitHub en tus actividades como investigador(a) de la mano de dos invetigadoras que son GitHub Stars!

### Sobre el curso

**Fecha** 18 de Noviembre de 2024, 2:00 PM - 5:00 PM (GMT-3)

**Modalidad**: Online

**Idioma:** Español

**Inscripción**: [Introducción a Github](https://www.eventbrite.com.ar/e/1045617188157)

Este taller está diseñado para introducir a investigadoras/es a GitHub, una potente plataforma para el control de versiones y la colaboración. Los participantes aprenderán los fundamentos del uso de GitHub para gestionar sus proyectos de investigación, incluyendo cómo crear y gestionar repositorios, realizar un seguimiento de los cambios y colaborar con otras personas.
Los objetivos específicos de aprendizaje incluyen:
  - Comprender los conceptos básicos del control de versiones y cómo se aplican a los flujos de trabajo de investigación.
  - Adquirir experiencia práctica en la creación y gestión de repositorios de GitHub.
  - Explorar el uso de GitHub Issues y Projects para gestionar las tareas de investigación y la comunicación dentro de los equipos de investigación.
  - Reconocer los diferentes componentes de un repositorio (readme, licencia, código de conducta, citas, entre otros).

Además, el taller hará hincapié en la relevancia de GitHub en la promoción de la ciencia abierta, destacando su papel como repositorio de código y datos que apoya la transparencia y la reproducibilidad en la investigación.
Al final del taller, los participantes serán capaces de integrar GitHub en sus flujos de trabajo de investigación, mejorando tanto la colaboración como la difusión abierta del conocimiento científico.

Este tutorial está dirigido a investigadoras/es de todas las disciplinas interesados en mejorar sus habilidades de gestión de proyectos y colaboración utilizando GitHub. Es ideal para quienes forman parte de equipos o grupos de investigación, con cierta familiaridad con los flujos de trabajo de investigación, pero no se requiere experiencia previa con GitHub.

### Requisitos
Los participantes deben disponer de un ordenador o portátil con acceso a Internet y almacenamiento suficiente para instalar Git. Deberán tener [Git instalado](https://git-scm.com/) y una [cuenta de GitHub](https://github.com/) creada antes del taller.

### Tutoras

**Beatriz Milz** - Beatriz es una GitHub Star, y actualmente es investigadora post-doctoral en la Universidade Federal do ABC (UFABC), en Brasil. Es doctora en Ciencias Ambientales por la Universidade de São Paulo (USP). Es coorganizadora de R-Ladies São Paulo y editora de revisión de software en rOpenSci».

**Yanina Bellini Saibene** - Yani es una GitHub Star desde 2022. Es Community Manager de rOpenSci, Líder del Proyecto R-Ladies y Vicepresidenta de la Junta Directiva de The Carpentries. Vive en Argentina y es profesora en la Universidad Austral (Argentina). Es organizadora de R-Ladies Santa Rosa y cofundadora y co-presidenta de LatinR. Yani es también formadora e instructora certificada por Posit y The Carpentries.



## Tutorial Análisis de Datos Satelitales en R

#### Aprende a realizar análisis de datos satelitales con R combinado con técnicas de Machine Learninig.

### Sobre el curso

**Fecha** 18 de Noviembre de 2024, 6:00 PM - 8:00 PM (GMT-3)

**Modalidad**: Online

**Idioma:** Español 

**Inscripción**: [Análisis de Datos Satelitales en R](https://www.eventbrite.com.ar/e/1045614801017)

El análisis de datos satelitales en R, combinado con técnicas de Machine Learning, abre nuevas oportunidades para interpretar y aprovechar la información geoespacial.
En este tutorial se abordarán aplicaciones prácticas utilizando R para procesar y analizar imágenes satelitales. Se demostrará cómo aprovechar librerías especializadas en R, como raster, sf y caret, para manipular datos espaciales y construir modelos predictivos. El uso de Machine Learning permitirá identificar patrones en grandes conjuntos de datos satelitales, aplicando algoritmos como árboles de decisión, SVM y Random Forest.
Se destacarán ejemplos reales en campos como la agricultura de precisión, monitoreo ambiental y detección de cambios en la superficie terrestre. La presentación enfatizará la importancia de integrar datos satelitales en la toma de decisiones y cómo estas técnicas permiten un análisis más eficiente y preciso de nuestro entorno desde el espacio.


### Tutora

**Gladis Choque Ulloa**

Tengo una maestría en estadística por la Universidad Federal de Rio Grande do Sul, Brasil, cuento con más de 5 años al mundo de los datos y la investigación. Actualmente soy estudiante becada en el doctorado en Estadística con enfoque en Ciencia de Datos en la Universidad de São Paulo, Brasil.

Mi especializo en modelos de series de tiempo y de clasificación en Machine Learning. Además, he escrito artículos sobre modelos predictivos y clasificación, y he tenido el honor de ganar el Concurso Internacional del Massachusetts Institute of Technology (MIT) en el 2020, fui dominada para el Women That Build Awards como Mujer destacada en Datos por Globant en el 2022, fui Expomentora en el NASA Space Apps Challangue Perú en el 2023, ganadora de los Clubes de Ciencia Brasil 2020 y ganadora como mejor trabajo de investigación del programa "Clean Water Science Network" de la Universidad de Texas, USA. Fundadora de la comunidad de datos Women in Datalab, Top Voice Data Science en Linkedln e influencer de data con el nombre de "Datos con Gladys" y "Gladys Data Club".


## Tutorial: Trabajando con datos más grandes que la memoria en R con Arrow y DuckDB

#### Aprende a analizar grandes conjuntos de datos con Arrow, DuckDB y Duckplyr en R.Acelera los flujos de trabajo en tu portátil usando manipulación de datos al estilo tidyverse.

### Sobre el curso

**Fecha** 19 de Noviembre de 2024, 10:00 AM - 12:00 AM (GMT-3)

**Modalidad**: Online

**Idioma:** Inglés 

**Inscripción**: [Tutorial con Arrow y DuckDB](https://www.eventbrite.com.ar/e/1044938257457)

Mientras que los conjuntos de datos son cada vez mayores, los recientes avances en tecnologías como Apache Arrow y DuckDB están poniendo al alcance de cualquiera el análisis de conjuntos de datos que antes requerían una infraestructura compleja.

El uso de los paquetes {arrow}, {duckdb} y {duckplyr} abre la puerta al análisis de gigabytes de datos en cuestión de segundos utilizando la misma interfaz que con {tidyverse}. Aprendiendo sólo unos pocos conceptos, los usuarios de R pueden disfrutar trabajando fácilmente con conjuntos de datos más grandes que la memoria directamente desde su ordenador de uso cotidiano.
En este tutorial, se analizarán datos reales para explorar los formatos utilizados para almacenar estos grandes conjuntos de datos en discos, cómo se pueden aprovechar Arrow y DuckDB para analizar datos, y cómo se integran estas herramientas con la interfaz de {tidyverse}.

Después de asistir a este tutorial, los alumnos
  - Comprenderán cuándo el uso de Arrow o DuckDB puede ayudar a acelerar un análisis de datos.
  - Describir cómo Arrow y DuckDB pueden trabajar con conjuntos de datos de mayor tamaño que la memoria.
  - Reconocer el tipo de manipulaciones de datos que más se benefician del uso de herramientas como Arrow y DuckDB.
  - Decidir qué paquete ({arrow}, {duckdb} o {duckplyr}) es el más adecuado para su análisis de datos.
  - Desarrollar su propio análisis de datos utilizando Arrow o DuckDB

Este tutorial está dirigido a todos aquellos que necesiten analizar conjuntos de datos mayores que la memoria de que disponen en su ordenador de uso cotidiano o que estén interesados en aprender a acelerar el análisis de grandes conjuntos de datos.
Los participantes que no tengan acceso a HPC se beneficiarán especialmente de este tutorial, ya que las herramientas utilizadas pueden instalarse fácilmente en un ordenador portátil normal y proporcionar un buen rendimiento.

### Requisitos
Los participantes deben estar familiarizados con la manipulación de datos con el {tidyverse} y saber utilizar los 5 verbos más comunes de {dplyr} para el análisis de datos: mutate(), select(), filter(), summarize(), arrange() combinados con group_by().

- **Software**: R >= 4.1.0

- **Paquetes**: arrow, duckdb, duckplyr, tidyverse, tictoc.

### Tutor

**François Michonneau** es un educador al que le encanta trabajar con datos y poner R en producción. Ha estado usando R durante más de 20 años y mantiene varios paquetes en CRAN. Después de formar parte de la dirección de The Carpentries durante 5 años, trabajó en Voltron Data durante un par de años. Actualmente está buscando su próximo rol.


## Tutorial Llevá tus gráficos con ggplot2 al siguiente nivel

#### Aprende como crear visualizaciones claras, informativas y cautivantes para tu analisis de datos.

### Sobre el curso

**Fecha** 19 de Noviembre de 2024, 2:00 PM - 4:30 PM (GMT-3)

**Modalidad**: Online

**Idioma:** Español  

**Inscripción**:  [Llevá tus gráficos con ggplot2 al siguiente nivel](https://www.eventbrite.com.ar/e/1045608201277)

Crear visualizaciones claras, informativas y cautivantes es una labor indiscutida dentro del análisis de datos, tanto dentro de la academia como de la industria. Sin embargo, la amplia mayoría de los tutoriales o de los cursos iniciales de R suelen explicar solamente cómo funciona la gramática de gráficos de ggplot2, sin abarcar la potencialidad de los parámetros estéticos que ayudan a comunicar de forma no verbal el objetivo del gráfico. En este taller vamos a mostrar cómo editar el texto y los colores, tanto de forma específica como a partir del uso de paletas, y cómo adaptar el gráfico a criterios específicos de publicación.

#### Objetivo general de aprendizaje:
Les participantes pueden adaptar sus gráficos a los requerimientos de publicación de una revista u otro formato académico.

### Objetivos específicos de aprendizaje:
Les participantes pueden modificar los elementos textuales de los gráficos.
Les participantes pueden editar el aspecto de los gráficos tanto a partir de la selección de colores específicos como del uso de paletas.
Les participantes pueden especificar las dimensiones de exportación de gráficos.

El tutorial está destinado a un público amplio que busque llevar sus gráficos al siguiente nivel por medio de la customización de etiquetas y textos, colores y detalles de los gráficos, sobre todo, para prepararlos de la mejor manera para presentaciones o publicaciones. En particular, este taller busca ayudar a quienes saben hacer un gráfico básico, pero no logran adaptarlo a sus necesidad específicas o que el gráfico muestre puntualmente lo que quieren.

### Requisitos

Para seguir sin problemas las actividades del tutorial, es necesario tener algún grado de experiencia, aunque sea inicial, con R y RStudio y con el paquete ggplot2. Además deberán tener una computadora con R y R Studio instalados y actualizados. Al igual que el paquete tidyverse, que incluye al paquete ggplot2, sobre el cual tratará el curso.

### Tutoras

**Noelia A. Stetie** es Profesora y Licenciada en Letras por la Universidad de Buenos Aires (UBA) y becaria doctoral del CONICET. Se dedica al estudio del procesamiento psicolingüístico del nivel oracional. Colabora en proyectos de investigación radicados en la UBA y se ha desempeñado como docente en dicha institución, en la Universidad Nacional de José C. Paz y en institutos de formación docente. Es Instructora certificada de The Carpentries y ha dictado diversos workshops sobre análisis de datos con R. Dicta cursos con foco en el análisis de datos y en la aplicación de teorías psicolingüísticas a la práctica docente.

**Macarena S. Quiroga** es Magister en Psicología Cognitiva y Aprendizaje por la Facultad Latinoamericana de Ciencias Sociales (FLACSO), Profesora y Licenciada en Letras por la Universidad de Buenos Aires (UBA) y becaria doctoral del CONICET. Se dedica al estudio de la comprensión y producción del vocabulario en niñes pequeñes. Es docente en la Universidad Nacional de Hurlingham. Es Trainer e Instructora certificada de The Carpentries y ha dictado diversos workshops sobre análisis de datos con R.


## Tutorial de modelización de nichos ecológicos y distribución potencial de especies con R

#### El tutorial cubrirá la teoría básica de la modelización del nicho ecológico y la distribución potencial de especies y sus principales metodologías.

### Sobre el curso

**Fecha** 19 de noviembre de 2024, 6:00 PM - 9:00 PM (GMT-3)

**Modalidad**: Online

**Idioma:** Portugués 

**Inscripción**: [Tutorial de modelización de nichos ecológicos](https://www.eventbrite.com.ar/e/1045601130127)

El tutorial cubrirá la teoría básica de la modelización de nichos ecológicos (ENM) y la modelización de la distribución de especies (SDM) y sus principales metodologías. Al final del curso, predominantemente práctico, los participantes tendrán la capacidad de ejecutar los modelos y comprender sus resultados, así como de elegir y aplicar la metodología correcta en función del objetivo de su tipo de estudio y de los datos. La tutoría será principalmente práctica, con algunos momentos teóricos. Todos los procesos de modelización, cálculos, gráficos y mapas se llevarán a cabo con R. Los participantes aprenderán a utilizar el algoritmo de modelización Maxent, a través del paquete {flexsdm} para desarrollar los modelos y se utilizará el paquete {tmap} para generar mapas.

### Objetivos:
   - Presentar las bases teóricas de los modelos que se pueden utilizar;
   - Discutir las ventajas y limitaciones de los modelos en el contexto de diferentes aplicaciones;
   - Presentar cómo realizar correctamente un estudio de modelización del nicho ecológico o de la distribución de especies con distintos fines;
   - Iniciar en el uso de la modelización de la distribución geográfica de especies utilizando R;

Estudiantes, investigadores y profesionales en cualquier etapa de su carrera con interés en desarrollar y aplicar la modelización de distribución de especies y/o nicho ecológico de forma reproducible y automatizada. Los participantes deben estar acostumbrados a trabajar con ordenadores, tener una buena conexión a Internet y, preferiblemente, una cámara web, ya que las sesiones en línea en directo están destinadas a ser altamente interactivas. Se recomienda tener experiencia básica con R, aunque no es estrictamente obligatorio. Todos los scripts de R serán proporcionados y explicados en detalle.

### Requisitos

Última versión de R y RStudio y paquetes que se enviarán por correo electrónico. 32MB RAM deseable, pero es posible ejecutar el script con 16MB.

### Tutor

**George Amaro** es investigador de la Empresa Brasileña de Investigación Agropecuaria (Embrapa), en el área de economía y modelización, y es líder y miembro de proyectos de modelización de la distribución de especies invasoras, revisor de revistas internacionales sobre el tema, con amplia experiencia en R y habiendo participado como autor y coautor de diversos trabajos relacionados con SDM/ENM.


## Optimizando Shiny: Consejos y Trucos de Rendimiento

#### Aprende cómo optimizar el rendimiento de aplicaciones desarrolladas con R Shiny de la mano de expertos de Appsilon.

### Sobre el curso

**Fecha** 18 de noviembre de 2024, 10:00 AM - 1:00 PM (GMT-3)

**Modalidad**: Online

**Inscripción**: [Optimizando Shiny: consejos y trucos de rendimiento](https://www.eventbrite.cl/e/optimizando-shiny-consejos-y-trucos-de-rendimiento-tickets-1045595392967)

**Idioma:** Español

En este workshop, exploraremos cómo optimizar el rendimiento de aplicaciones desarrolladas con R Shiny, desde mejorar la velocidad de respuesta hasta la escalabilidad.

A través de ejemplos prácticos y técnicas avanzadas, identificaremos los cuellos de botella más comunes, para minimizar tiempos de carga y gestionar grandes volúmenes de datos de manera eficiente.

También abordaremos las mejores prácticas para optimizar tanto el código como la estructura de la aplicación, incluyendo el uso adecuado de reactividad, carga de datos, y comunicación con el navegador.

Al finalizar el taller, tendrás las herramientas necesarias para transformar tus aplicaciones Shiny, haciéndolas más rápidas, ligeras y listas para brindar una mejor experiencia de usuario.


Este taller está dirigido a desarrolladores y analistas que buscan mejorar el rendimiento de sus aplicaciones Shiny, con un enfoque práctico y orientado a resultados.

### Requisitos

R 4.1.0 o mayor, RStudio instalado. 8GB RAM (deseable), internet estable (deseable). Git instalado (deseable). Alternativamente, tener una cuenta en posit.cloud.

### Tutor

[**Samuel Calderon**](https://www.linkedin.com/in/samuelcalderon/) actualmente trabaja como R shiny developer en Appsilon. Previamente, su desempeño profesional ha sido en el sector público peruano, participando en iniciativas de recojo, análisis y sistematización de información con miras a mejorar la calidad de los servicios brindados a la ciudadanía en temas de lucha contra el tráfico ilícito de drogas, mejora de la calidad de la educación superior universitaria, lucha contra la corrupción y medición de la pobreza monetaria.

## Despliegue Continuo con R, GitHub y Quarto: Implementando Buenas Prácticas

#### Aprende cómo implementar un flujo de trabajo de despliegue continuo para modelos de datos en R utilizando GitHub y Quarto

### Sobre el curso

**Fecha** 18 de noviembre de 2024, 06:00 PM - 08:00 PM (GMT-3)

**Modalidad**: Online

**Inscripción**: [Despliegue continuo con R, Github y Quarto](https://www.eventbrite.cl/e/despliegue-continuo-con-r-github-y-quarto-implementando-buenas-practicas-tickets-1046364954747)

**Idioma:** Español

Este taller tiene como objetivo enseñar a los participantes a implementar un flujo de trabajo de despliegue continuo para modelos de datos en R utilizando GitHub y Quarto. Al final de la sesión, los asistentes serán capaces de:

Configurar un entorno de R en GitHub Actions para automatizar la ejecución de scripts.
Instalar y gestionar dependencias de R de manera eficiente.
Generar y renderizar informes en Quarto, facilitando la presentación de resultados.
Integrar buenas prácticas de DevOps en sus flujos de trabajo para mejorar la colaboración y la calidad del código.

La relevancia de este taller radica en la creciente necesidad de automatización en el análisis de datos y la ciencia de datos. Aprender a utilizar GitHub Actions y Quarto no solo optimiza el trabajo en equipo, sino que también permite a los participantes implementar soluciones robustas y escalables para la evaluación de métricas y el análisis de resultados. Este conocimiento es fundamental para quienes buscan mejorar la reproducibilidad de sus proyectos y la eficiencia de sus procesos de análisis.


El taller está dirigido a profesionales y estudiantes de áreas como ciencia de datos, estadística, análisis de datos y programación en R. También es relevante para investigadores y desarrolladores interesados en optimizar sus flujos de trabajo mediante la automatización y la implementación de buenas prácticas de DevOps.

Los participantes deben tener conocimientos básicos de programación en R y familiaridad con Git y GitHub. También es recomendable que tengan conocimientos basicos en generación de documentos en R, ya sea usando Rmarkdown o Quarto.

### Requisitos

Para participar de forma óptima en el taller de Despliegue Continuo con R, GitHub y Quarto, los asistentes deben contar con una computadora portátil (Windows, macOS o Linux) y tener instalado el software necesario, que incluye R, RStudio, Git y Quarto. Además, es importante tener acceso a Internet y una cuenta de GitHub previamente creada. Se recomienda asegurarse de tener acceso a los archivos de ejemplo que se utilizarán durante el taller. Aunque no es estrictamente necesario, tener conocimientos básicos de R y Git, así como familiaridad con Markdown, será útil para aprovechar al máximo la experiencia.

### Tutor

**Sebastián Egaña Santibáñez** es Magíster en Finanzas por la Universidad de Chile, Licenciado en Filosofía por la Universidad Alberto Hurtado y Ingeniero Comercial por la Universidad Santo Tomás, Chile.

Es un profesional destacado en Ciencia de Datos, con una sólida trayectoria como docente universitario y experiencia en asesoría especializada. Ha contribuido significativamente a la formación académica y a la aplicación práctica del análisis de datos, ofreciendo soluciones innovadoras y estratégicas en diversos contextos.

## Desarrollo de Paquetes en R: Desde la Idea hasta la Implementación

#### Aprende cómo desarrollar paquetes de R, como implementarlos y distribuirlos.

### Sobre el curso

**Fecha** 19 de noviembre de 2024, 10:00 AM - 1:00 PM (GMT-3)

**Modalidad**: Online

**Inscripción**: [Desarrollo de Paquetes en R](https://www.eventbrite.cl/e/desarrollo-de-paquetes-en-r-desde-la-idea-hasta-la-implementacion-tickets-1046361845447)

**Idioma:** Español

Este taller ofrece una guía integral sobre el desarrollo de paquetes en R, cubriendo todo el proceso, desde la concepción de la idea hasta la implementación técnica y la distribución en plataformas como CRAN.

El objetivo es brindar a los asistentes una comprensión clara y práctica de cómo crear un paquete en R que cumpla con los estándares de calidad y pueda ser utilizado por la comunidad científica y de desarrollo.

A lo largo de la presentación, exploraremos las mejores prácticas para el diseño, documentación, pruebas, y publicación de paquetes. Se proporcionarán ejemplos y demostraciones en vivo para que los asistentes puedan adquirir habilidades prácticas aplicables en sus propios proyectos.

El tutorial esta enfocado en usuario de R, desarrolladores de R, investigadores, científicos de datos y profesionales de otras disciplinas que pueden tomar su conocimiento, experiencias y datos y convertirlos en un paquete de R para su publicación en el CRAN.


### Requisitos

PC o Laptop con R, RStudio y RTools (windows) instalados y paquetes: devtools, available, usethis, testthat.

### Tutor

**Renzo Cáceres Rossi**, es un especialista en el lenguaje de programación R, ya ha participado en el Latin R 2022 con la ponencia Introducción a RMarkdown, ha dictado tutoriales, conferencias en diversas universidades en Latinoamérica a través del IEEE.


Es creador de contenido sobre ciencia de datos a través de [su canal de YouTube.](https://www.youtube.com/c/RenzoCaceresRossi)