---
title: "Conferencias"
knitr:
  opts_chunk: 
    echo: false
    message: false
    warning: false
---


```{css echo=FALSE}
.card-header-keynote{
  background-color: #FDC08666;
  font-weight: bold;
}

.cards-display{
  display: grid;
}

.html-fill-container > .html-fill-item {
  flex: inherit;
}
```

En esta octava edición de la conferencia contaremos con la presencia de oradores que son referentes en el área de programación con R, con experiencia tanto en el ámbito académico como en la industria y en organizaciones de la sociedad civil. Se destacan por su compromiso con la colaboración y la promoción de ciencia, datos y sofware abiertos. 


## Conferencistas

```{r}
#| results: asis
source(here::here("R/generar-info-keynotes.R"))
info_keynotes <- generar_info_keynotes()

generar_cards_keynotes(info_keynotes = info_keynotes, col_information = "info_es")

```

## Conferencias

### Heather Turne: Lowering Barriers to Contributing to R

It is 30 years since R was released under an open source license and
today R is  used by millions of people worldwide. Ensuring that R remains a solid foundation for people's work requires ongoing development and maintenance. The general R community can play an important part in sustaining R for the future. In this keynote, I'll share some recent initiatives that lower barriers to contribution. We'll explore two tools that simplify the process of contributing:  

Weblate for contributing translations of errors, warnings and messages, and the R Dev Container for contributing to the code and documentation. These tools require minimal setup, so you can focus on the interesting work! We'll discover how these tools have been used by participants at collaborative events - translation hackathons and R Dev Days - organised by the R Contribution Working Group in recent years. Finally, I'll discuss how you can find tasks, get support, and start contributing, so that together we can ensure R continues to thrive for decades to come.

<!-- font awesome -->

```{=html}
<script src="https://kit.fontawesome.com/1f72d6921a.js" crossorigin="anonymous"></script>
```
<!-- font awesome -->