---
title: "Palestras convidadas"
knitr:
  opts_chunk: 
    echo: false
    message: false
    warning: false
---


```{css echo=FALSE}
.card-header-keynote{
  background-color: #FDC08666;
  font-weight: bold;
}

.cards-display{
  display: grid;
}

.html-fill-container > .html-fill-item {
  flex: inherit;
}
```

Nesta oitava edição, contaremos com a presença de palestrantes proeminentes no campo da programação com R, com experiência tanto na academia quanto na indústria, comprometidos com a colaboração e a promoção da ciência, dados e software abertos. 

## Palestrantes

```{r}
#| results: asis
source(here::here("R/generar-info-keynotes.R"))
info_keynotes <- generar_info_keynotes()
generar_cards_keynotes(info_keynotes = info_keynotes, col_information = "info_pt")

```


## Palestras


### Heather Turner: Lowering Barriers to Contributing to R

It is 30 years since R was released under an open source license and
today R is  used by millions of people worldwide. Ensuring that R remains a solid foundation for people's work requires ongoing development and maintenance. The general R community can play an important part in sustaining R for the future. In this keynote, I'll share some recent initiatives that lower barriers to contribution. We'll explore two tools that simplify the process of contributing:  

Weblate for contributing translations of errors, warnings and messages, and the R Dev Container for contributing to the code and documentation. These tools require minimal setup, so you can focus on the interesting work! We'll discover how these tools have been used by participants at collaborative events - translation hackathons and R Dev Days - organised by the R Contribution Working Group in recent years. Finally, I'll discuss how you can find tasks, get support, and start contributing, so that together we can ensure R continues to thrive for decades to come.

### Stephanie Zimmer: Transforming a team to open-source first

Three years ago, a small group at my work formed an open-source software committee in a land where statisticians primarily used a commercially available software. We wanted to champion an open-source first initiative and convert people and projects to using open-source software. I will talk about what we did to make this happen and how the process accelerated. Some of the key things I was involved in were open-source office hours which formed a great community, developing an R package when we couldn't find something we needed in R, and developing small examples of common things we do in our work in R with a comparison to the prior method.


<!-- font awesome -->

```{=html}
<script src="https://kit.fontawesome.com/1f72d6921a.js" crossorigin="anonymous"></script>
```
<!-- font awesome -->